name: Download CS Game Files

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true # Если используете Git LFS для больших файлов

      - uses: actions/setup-node@v3

      - name: Установка зависимостей
        run: npm install

      - name: Запуск скрипта для загрузки файлов
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node index.js "$USERNAME" "$PASSWORD"

      - name: Запуск декомпилятора
        run: |
          if [ -f "./temp/pak01_dir.vpk" ]; then
            chmod +x ./Decompiler
            ./Decompiler -i "./temp/pak01_dir.vpk" -o "./static" -e "vtex_c" -d -f "panorama/images/econ" --skip-existing
          else
            echo "pak01_dir.vpk не найден, пропускаем декомпиляцию"
          fi

      - name: Настройка Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Добавление изменений
        run: |
          git add ./static
          git diff-index --quiet HEAD || git commit -m "Обновление статических файлов"

      - name: Push изменений
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
