name: Download CS Game Files

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true # Если используете Git LFS для больших файлов

      - uses: actions/setup-node@v3

      - name: Установка зависимостей
        run: npm install

      - name: Запуск скрипта для загрузки файлов
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node index.js "$USERNAME" "$PASSWORD"

      - name: Запуск декомпилятора
        run: |
          if [ -f "./temp/pak01_dir.vpk" ]; then
            chmod +x ./Decompiler
            # Используем find для поиска новых VPK-файлов и декомпилируем их по одному
            for vpk_file in ./temp/pak01_*.vpk; do
              if [ -f "$vpk_file" ]; then
                # Проверяем, были ли файлы уже декомпилированы
                output_dir="./static/$(basename "$vpk_file" .vpk)"
                if [ ! -d "$output_dir" ]; then
                  mkdir -p "$output_dir"
                  ./Decompiler -i "$vpk_file" -o "$output_dir" -e "vtex_c" -d -f "panorama/images/econ"
                else
                  echo "Директория $output_dir уже существует, пропускаем декомпиляцию."
                fi
              fi
            done
          else
            echo "pak01_dir.vpk не найден, пропускаем декомпиляцию"
          fi

      - name: Настройка Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Добавление изменений
        run: |
          git add ./static
          git diff-index --quiet HEAD || git commit -m "Обновление статических файлов"

      - name: Push изменений
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
