name: Download Dota Game Files

on:
  schedule:
<<<<<<< HEAD:.github/workflows/download-dota-files.yml
    - cron: "50 7 * * *"
=======
     - cron: "50 7 * * *" # Запускается каждый день в 8 утра по UTC
>>>>>>> 0dda5f72ff7086cd8b4278ebf29bee5a1f669684:.github/workflows/workflow.yml

  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
<<<<<<< HEAD:.github/workflows/download-dota-files.yml
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
=======
      contents: write  # Разрешает токену GITHUB_TOKEN записывать изменения

    steps:
      - uses: actions/checkout@v3  # Проверка репозитория
      - uses: actions/setup-node@v3  # Настройка Node.js
>>>>>>> 0dda5f72ff7086cd8b4278ebf29bee5a1f669684:.github/workflows/workflow.yml

      - name: Download new game files
        run: npm install && node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}'

      - name: Run Decompiler for pak01_dir.vpk with ValveResourceFormat 8.1
        run: |
          if [ -f "./temp/pak01_dir.vpk" ]; then
            chmod +x ./Decompiler
            ./Decompiler -i "./temp/pak01_dir.vpk" -o "./static" -e "vtex_c" -d -f "panorama/images/econ"
          else
            echo "pak01_dir.vpk not found, skipping decompilation"
          fi

      - name: Read manifestId.txt
        id: manifestId
        uses: juliangruber/read-file-action@v1
        with:
          path: ./static/manifestId.txt

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "manifest ${{ steps.manifestId.outputs.content }}"
