name: Download Dota Game Files

on:
  schedule:
    - cron: "0 8 * * *"

  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      contents: write # To commit and push changes back to the repository

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true # Keeps GitHub token for git push
      - uses: actions/setup-node@v3
      - name: Set up git user
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
      - name: Install dependencies
        run: npm install
      - name: Ensure Decompiler is executable
        run: chmod +x ./Decompiler
      - name: Process VPK files in batches
        run: |
          while true; do
            # Run the index.js script and prevent failure on non-zero exit code
            node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}' || true

            # Читаем статус партии
            BATCH_STATUS=$(cat batch_status.txt)
            echo "Batch Status: $BATCH_STATUS"

            if [ "$BATCH_STATUS" = "DONE" ]; then
              echo "All VPK files processed."
              break
            fi

            # Проверяем, существует ли файл pak01_dir.vpk
            if [ -f "./temp/pak01_dir.vpk" ]; then
              # Запуск декомпилятора
              ./Decompiler -i "./temp/pak01_dir.vpk" -o "./static" -e "vtex_c" -d -f "panorama/images/econ"
            else
              echo "pak01_dir.vpk not found, skipping decompilation"
            fi

            # Коммитим только новые файлы
            git add -A --ignore-errors  # Добавляем все новые файлы
            git diff --cached --name-only --diff-filter=A | xargs git add  # Коммитим только добавленные файлы
            git commit -m "Processed batch $(date +"%Y-%m-%d %H:%M:%S")" || echo "No new files to commit"
            git push

            # Очистка временных файлов для следующей партии
            rm -rf ./temp/*
          done
      - name: Final Commit
        if: ${{ steps.checkout.outputs.changed == 'true' }}
        run: |
          git add .
          git commit -m "Final commit after all batches"
          git push
