name: Download Dota Images

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16" # или другая подходящая версия Node.js
      - name: Install dependencies
        run: npm install
      - name: Ensure Decompiler is executable
        run: chmod +x ./Decompiler
      - name: Run script
        run: node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}'
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update manifest ID to ${{ steps.manifestId.outputs.content }}"
